### ISSUE TITLE
Email regexen are flat out wrong

### ISSUE THREAD

**Issue by RandalSchwartz** [agungnursatria/regexpattern#2]
These:
 ```
static Pattern username = r'^[a-zA-Z0-9][a-zA-Z0-9_.]+[a-zA-Z0-9]$';

  /// Email regex
  static Pattern email =
      r'^[a-z0-9]+([-+._][a-z0-9]+){0,2}@.*?(\.(a(?:[cdefgilmnoqrstuwxz]|ero|(?:rp|si)a)|b(?:[abdefghijmnorstvwyz]iz)|c(?:[acdfghiklmnoruvxyz]|at|o(?:m|op))|d[ejkmoz]|e(?:[ceghrstu]|du)|f[ijkmor]|g(?:[abdefghilmnpqrstuwy]|ov)|h[kmnrtu]|i(?:[delmnoqrst]|n(?:fo|t))|j(?:[emop]|obs)|k[eghimnprwyz]|l[abcikrstuvy]|m(?:[acdeghklmnopqrstuvwxyz]|il|obi|useum)|n(?:[acefgilopruz]|ame|et)|o(?:m|rg)|p(?:[aefghklmnrstwy]|ro)|qa|r[eosuw]|s[abcdeghijklmnortuvyz]|t(?:[cdfghjklmnoprtvwz]|(?:rav)?el)|u[agkmsyz]|v[aceginu]|w[fs]|y[etu]|z[amw])\b){1,2}$';
```

are flat out wrong.  The shortest single regex that mostly gets an email address correct is in https://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html.  (Doesn't handle comments or nested comments, but that's a different story.)

If you want to provide a proper matching on email, consider https://pub.dev/packages/email_validator, which actually generates a regex like that long one internally.

Stop propagating the myth of limited characters on the left or right side of the "@"!

**Comment by agungnursatria** [comment]
Updated in v2.2.0

**Comment by RandalSchwartz** [comment]
It's still wrong.

**Comment by InstrinsicAutomations** [comment]
Confirmed it is not handling multiple `@` correctly.
